print("=== MENÚ SISTEMA DE VENTAS ===")
print("1. Registrar producto")
print("2. Consultar producto")
print("3. Subtotal calcular")
print("4. Salir")
Precio = float(input("Precio: $"))
cantidad = int(input("Cantidad: "))
print("Subtotal:", Precio * cantidad)
input("Entra para salir")
