print("=== MENU SISTEMA DE VENTAS ===")
print("1. Registrar producto")
print("2. Consultar producto")
print("3. Calcular subtotal")
print("4. Salir")
precio = float(input("Precio: $"))
cantidad = int(input("Cantidad: "))
print("Subtotal:", precio * cantidad)
input("Enter para salir")
